src/Entity/Countries.php
<?php

namespace App\Entity;

use App\Repository\CountriesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CountriesRepository::class)]
class Countries
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * @var Collection<int, Movies>
     */
    #[ORM\ManyToMany(targetEntity: Movies::class, inversedBy: 'countries')]
    private Collection $id_country;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $country_name = null;

    public function __construct()
    {
        $this->id_country = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Movies>
     */
    public function getIdCountry(): Collection
    {
        return $this->id_country;
    }

    public function addIdCountry(Movies $idCountry): static
    {
        if (!$this->id_country->contains($idCountry)) {
            $this->id_country->add($idCountry);
        }

        return $this;
    }

    public function removeIdCountry(Movies $idCountry): static
    {
        $this->id_country->removeElement($idCountry);

        return $this;
    }

    public function getCountryName(): ?string
    {
        return $this->country_name;
    }

    public function setCountryName(?string $country_name): static
    {
        $this->country_name = $country_name;

        return $this;
    }
}

src/Form/CountriesType.php
<?php

namespace App\Form;

use App\Entity\Countries;
use App\Entity\movies;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CountriesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('country_name')
            ->add('id_country', EntityType::class, [
                'class' => movies::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Countries::class,
        ]);
    }
}

src/Controller/CountriesController.php
<?php

namespace App\Controller;

use App\Entity\Countries;
use App\Form\CountriesType;
use App\Repository\CountriesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/countries')]
final class CountriesController extends AbstractController
{
    #[Route(name: 'app_countries_index', methods: ['GET'])]
    public function index(CountriesRepository $countriesRepository): Response
    {
        return $this->render('countries/index.html.twig', [
            'countries' => $countriesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_countries_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $country = new Countries();
        $form = $this->createForm(CountriesType::class, $country);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($country);
            $entityManager->flush();

            return $this->redirectToRoute('app_countries_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('countries/new.html.twig', [
            'country' => $country,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_countries_show', methods: ['GET'])]
    public function show(Countries $country): Response
    {
        return $this->render('countries/show.html.twig', [
            'country' => $country,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_countries_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Countries $country, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CountriesType::class, $country);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_countries_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('countries/edit.html.twig', [
            'country' => $country,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_countries_delete', methods: ['POST'])]
    public function delete(Request $request, Countries $country, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$country->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($country);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_countries_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/countries/_delete_form.html.twig
<form method="post" action="{{ path('app_countries_delete', {'id': country.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ country.id) }}">
    <button class="btn">Delete</button>
</form>

templates/countries/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/countries/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Countries{% endblock %}

{% block body %}
    <main class="main"> 
    <h1>Edit Countries</h1>

    {{ include('countries/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_countries_index') }}">back to list</a>

    {{ include('countries/_delete_form.html.twig') }}
    </main>
{% endblock %}

templates/countries/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Countries index{% endblock %}

{% block body %}
        <main class="main"> 
    
    <h1>Countries index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Country_name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for country in countries %}
            <tr>
                <td>{{ country.id }}</td>
                <td>{{ country.countryName }}</td>
                <td>
                    <a href="{{ path('app_countries_show', {'id': country.id}) }}">show</a>
                    <a href="{{ path('app_countries_edit', {'id': country.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_countries_new') }}">Create new</a>
    </main>   
{% endblock %}

templates/countries/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Countries{% endblock %}

{% block body %}
    <main class="main"> 
    <h1>Create new Countries</h1>

    {{ include('countries/_form.html.twig') }}

    <a href="{{ path('app_countries_index') }}">back to list</a>
    </main>
{% endblock %}

templates/countries/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Countries{% endblock %}

{% block body %}
    <main class="main"> 
    <h1>Countries</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ country.id }}</td>
            </tr>
            <tr>
                <th>Country_name</th>
                <td>{{ country.countryName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_countries_index') }}">back to list</a>

    <a href="{{ path('app_countries_edit', {'id': country.id}) }}">edit</a>

    {{ include('countries/_delete_form.html.twig') }}
    </main>
{% endblock %}