src/Entity/Awards.php
<?php

namespace App\Entity;

use App\Repository\AwardsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AwardsRepository::class)]
class Awards
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 200, nullable: true)]
    private ?string $award_name = null;

    #[ORM\Column(nullable: true)]
    private ?int $award_year = null;

    /**
     * @var Collection<int, Movies>
     */
    #[ORM\ManyToMany(targetEntity: Movies::class, inversedBy: 'awards_won')]
    private Collection $id_award;

    public function __construct()
    {
        $this->id_award = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAwardName(): ?string
    {
        return $this->award_name;
    }

    public function setAwardName(?string $award_name): static
    {
        $this->award_name = $award_name;

        return $this;
    }

    public function getAwardYear(): ?int
    {
        return $this->award_year;
    }

    public function setAwardYear(?int $award_year): static
    {
        $this->award_year = $award_year;

        return $this;
    }

    /**
     * @return Collection<int, Movies>
     */
    public function getIdAward(): Collection
    {
        return $this->id_award;
    }

    public function addIdAward(Movies $idAward): static
    {
        if (!$this->id_award->contains($idAward)) {
            $this->id_award->add($idAward);
        }

        return $this;
    }

    public function removeIdAward(Movies $idAward): static
    {
        $this->id_award->removeElement($idAward);

        return $this;
    }
}

src/Form/AwardsType.php
<?php

namespace App\Form;

use App\Entity\Awards;
use App\Entity\movies;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AwardsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('award_name')
            ->add('award_year')
            ->add('id_award', EntityType::class, [
                'class' => movies::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Awards::class,
        ]);
    }
}

src/Controller/AwardsController.php
<?php

namespace App\Controller;

use App\Entity\Awards;
use App\Form\AwardsType;
use App\Repository\AwardsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/awards')]
final class AwardsController extends AbstractController
{
    #[Route(name: 'app_awards_index', methods: ['GET'])]
    public function index(AwardsRepository $awardsRepository): Response
    {
        return $this->render('awards/index.html.twig', [
            'awards' => $awardsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_awards_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $award = new Awards();
        $form = $this->createForm(AwardsType::class, $award);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($award);
            $entityManager->flush();

            return $this->redirectToRoute('app_awards_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('awards/new.html.twig', [
            'award' => $award,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_awards_show', methods: ['GET'])]
    public function show(Awards $award): Response
    {
        return $this->render('awards/show.html.twig', [
            'award' => $award,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_awards_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Awards $award, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AwardsType::class, $award);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_awards_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('awards/edit.html.twig', [
            'award' => $award,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_awards_delete', methods: ['POST'])]
    public function delete(Request $request, Awards $award, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$award->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($award);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_awards_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/awards/_delete_form.html.twig
<form method="post" action="{{ path('app_awards_delete', {'id': award.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ award.id) }}">
    <button class="btn">Delete</button>
</form>

templates/awards/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/awards/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Awards{% endblock %}

{% block body %}
    <main class="main"> 
    <h1>Edit Awards</h1>

    {{ include('awards/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_awards_index') }}">back to list</a>

    {{ include('awards/_delete_form.html.twig') }}
    </main>
{% endblock %}

templates/awards/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Awards index{% endblock %}

{% block body %}
        <main class="main"> 
    <h1>Awards index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Award_name</th>
                <th>Award_year</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for award in awards %}
            <tr>
                <td>{{ award.id }}</td>
                <td>{{ award.awardName }}</td>
                <td>{{ award.awardYear }}</td>
                <td>
                    <a href="{{ path('app_awards_show', {'id': award.id}) }}">show</a>
                    <a href="{{ path('app_awards_edit', {'id': award.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_awards_new') }}">Create new</a>
    </main>    
{% endblock %}

templates/awards/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Awards{% endblock %}

{% block body %}
    <main class="main"> 
    <h1>Create new Awards</h1>

    {{ include('awards/_form.html.twig') }}

    <a href="{{ path('app_awards_index') }}">back to list</a>
    </main>
{% endblock %}

templates/awards/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Awards{% endblock %}

{% block body %}
    <main class="main"> 
    <h1>Awards</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ award.id }}</td>
            </tr>
            <tr>
                <th>Award_name</th>
                <td>{{ award.awardName }}</td>
            </tr>
            <tr>
                <th>Award_year</th>
                <td>{{ award.awardYear }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_awards_index') }}">back to list</a>

    <a href="{{ path('app_awards_edit', {'id': award.id}) }}">edit</a>

    {{ include('awards/_delete_form.html.twig') }}
    </main>
{% endblock %}