src/Entity/Movies.php
<?php

namespace App\Entity;

use App\Repository\MoviesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: MoviesRepository::class)]
class Movies
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 200, nullable: true)]
    private ?string $poster = null;

    #[Vich\UploadableField(mapping: 'uploads', fileNameProperty: 'poster')]
    private ?File $posterFile = null;

    #[ORM\Column(length: 250, nullable: true)]
    private ?string $french_title = null;

    #[ORM\Column(length: 250, nullable: true)]
    private ?string $original_title = null;

    #[ORM\Column(nullable: true)]
    private ?int $year = null;

    #[ORM\Column(length: 200, nullable: true)]
    private ?string $prod_countries = null;

    #[ORM\Column(nullable: true)]
    private ?int $duration = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $pitch = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $review = null;

    /**
     * @var Collection<int, Awards>
     */
    #[ORM\ManyToMany(targetEntity: Awards::class, mappedBy: 'id_award')]
    private Collection $awards_won;

    /**
     * @var Collection<int, Countries>
     */
    #[ORM\ManyToMany(targetEntity: Countries::class, mappedBy: 'id_country')]
    private Collection $countries;

    /**
     * @var Collection<int, Casting>
     */
    #[ORM\ManyToMany(targetEntity: Casting::class, mappedBy: 'id_cast')]
    private Collection $castings;

    /**
     * @var Collection<int, Categories>
     */
    #[ORM\ManyToMany(targetEntity: Categories::class, mappedBy: 'id_category')]
    private Collection $id_categories;

    public function __construct()
    {
        $this->awards_won = new ArrayCollection();
        $this->countries = new ArrayCollection();
        $this->castings = new ArrayCollection();
        $this->id_categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(?string $poster): static
    {
        $this->poster = $poster;

        return $this;
    }

    public function setPosterFile(?File $posterfile = null): void
    {
        $this->posterFile = $posterfile;
    }

    public function getPosterFile(): ?File
    {
        return $this->posterFile;
    }

    public function getFrenchTitle(): ?string
    {
        return $this->french_title;
    }

    public function setFrenchTitle(?string $french_title): static
    {
        $this->french_title = $french_title;

        return $this;
    }

    public function getOriginalTitle(): ?string
    {
        return $this->original_title;
    }

    public function setOriginalTitle(?string $original_title): static
    {
        $this->original_title = $original_title;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): static
    {
        $this->year = $year;

        return $this;
    }

    public function getProdCountries(): ?string
    {
        return $this->prod_countries;
    }

    public function setProdCountries(?string $prod_countries): static
    {
        $this->prod_countries = $prod_countries;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(?int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getPitch(): ?string
    {
        return $this->pitch;
    }

    public function setPitch(?string $pitch): static
    {
        $this->pitch = $pitch;

        return $this;
    }

    public function getReview(): ?string
    {
        return $this->review;
    }

    public function setReview(?string $review): static
    {
        $this->review = $review;

        return $this;
    }

    /**
     * @return Collection<int, Awards>
     */
    public function getAwardsWon(): Collection
    {
        return $this->awards_won;
    }

    public function addAwardsWon(Awards $awardsWon): static
    {
        if (!$this->awards_won->contains($awardsWon)) {
            $this->awards_won->add($awardsWon);
            $awardsWon->addIdAward($this);
        }

        return $this;
    }

    public function removeAwardsWon(Awards $awardsWon): static
    {
        if ($this->awards_won->removeElement($awardsWon)) {
            $awardsWon->removeIdAward($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Countries>
     */
    public function getCountries(): Collection
    {
        return $this->countries;
    }

    public function addCountry(Countries $country): static
    {
        if (!$this->countries->contains($country)) {
            $this->countries->add($country);
            $country->addIdCountry($this);
        }

        return $this;
    }

    public function removeCountry(Countries $country): static
    {
        if ($this->countries->removeElement($country)) {
            $country->removeIdCountry($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Casting>
     */
    public function getCastings(): Collection
    {
        return $this->castings;
    }

    public function addCasting(Casting $casting): static
    {
        if (!$this->castings->contains($casting)) {
            $this->castings->add($casting);
            $casting->addIdCast($this);
        }

        return $this;
    }

    public function removeCasting(Casting $casting): static
    {
        if ($this->castings->removeElement($casting)) {
            $casting->removeIdCast($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Categories>
     */
    public function getIdCategories(): Collection
    {
        return $this->id_categories;
    }

    public function addIdCategory(Categories $idCategory): static
    {
        if (!$this->id_categories->contains($idCategory)) {
            $this->id_categories->add($idCategory);
            $idCategory->addIdCategory($this);
        }

        return $this;
    }

    public function removeIdCategory(Categories $idCategory): static
    {
        if ($this->id_categories->removeElement($idCategory)) {
            $idCategory->removeIdCategory($this);
        }

        return $this;
    }
}

src/Form/MoviesType.php
<?php

namespace App\Form;

use App\Entity\Awards;
use App\Entity\Casting;
use App\Entity\Categories;
use App\Entity\Countries;
use App\Entity\Movies;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Vich\UploaderBundle\Form\Type\VichImageType;

class MoviesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('posterFile', VichImageType::class, [
                'required' => false,
                'allow_delete' => true,
                'delete_label' => '...',
                'download_label' => '...',
                'download_uri' => true,
                'image_uri' => true,
                'asset_helper' => true,
            ], null, array('label' => false))
            ->add('french_title')
            ->add('original_title')
            ->add('year')
            ->add('prod_countries')
            ->add('duration')
            ->add('pitch')
            ->add('review')
            ->add('awards_won', EntityType::class, [
                'class' => Awards::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
            ->add('countries', EntityType::class, [
                'class' => Countries::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
            ->add('castings', EntityType::class, [
                'class' => Casting::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
            ->add('id_categories', EntityType::class, [
                'class' => Categories::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Movies::class,
        ]);
    }
}

src/Controller/MoviesController.php
<?php

namespace App\Controller;

use App\Entity\Movies;
use App\Form\MoviesType;
use App\Repository\MoviesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/movies')]
final class MoviesController extends AbstractController
{
    #[Route(name: 'app_movies_index', methods: ['GET'])]
    public function index(MoviesRepository $moviesRepository): Response
    {
        return $this->render('movies/index.html.twig', [
            'movies' => $moviesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_movies_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $movie = new Movies();
        $form = $this->createForm(MoviesType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($movie);
            $entityManager->flush();

            return $this->redirectToRoute('app_movies_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('movies/new.html.twig', [
            'movie' => $movie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_movies_show', methods: ['GET'])]
    public function show(Movies $movie): Response
    {
        return $this->render('movies/show.html.twig', [
            'movie' => $movie,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_movies_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Movies $movie, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MoviesType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_movies_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('movies/edit.html.twig', [
            'movie' => $movie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_movies_delete', methods: ['POST'])]
    public function delete(Request $request, Movies $movie, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$movie->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($movie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_movies_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/movies/_delete_form.html.twig
<form method="post" action="{{ path('app_movies_delete', {'id': movie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ movie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/movies/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/movies/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Movies{% endblock %}

{% block body %}
    <main class="main"> 
    <h1>Edit Movies</h1>

    {{ include('movies/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_movies_index') }}">back to list</a>

    {{ include('movies/_delete_form.html.twig') }}
    </main> 
{% endblock %}

templates/movies/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Movies index{% endblock %}

{% block body %}
        <main class="main"> 
    <h1>Movies index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Poster</th>
                <th>French_title</th>
                <th>Original_title</th>
                <th>Year</th>
                <th>Prod_countries</th>
                <th>Duration</th>
                <th>Pitch</th>
                <th>Review</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for movie in movies %}
            <tr>
                <td>{{ movie.id }}</td>
                <td>{{ movie.poster }}</td>
                <td>{{ movie.frenchTitle }}</td>
                <td>{{ movie.originalTitle }}</td>
                <td>{{ movie.year }}</td>
                <td>{{ movie.prodCountries }}</td>
                <td>{{ movie.duration }}</td>
                <td>{{ movie.pitch }}</td>
                <td>{{ movie.review }}</td>
                <td>
                    <a href="{{ path('app_movies_show', {'id': movie.id}) }}">show</a>
                    <a href="{{ path('app_movies_edit', {'id': movie.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_movies_new') }}">Create new</a>
    </main>   
{% endblock %}

templates/movies/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Movies{% endblock %}

{% block body %}
    <main class="main"> 
    <h1>Create new Movies</h1>

    {{ include('movies/_form.html.twig') }}

    <a href="{{ path('app_movies_index') }}">back to list</a>
    </main>    
{% endblock %}

templates/movies/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Movies{% endblock %}

{% block body %}
        <main class="main"> 
       
    <h1>Movies</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ movie.id }}</td>
            </tr>
            <tr>
                <th>Poster</th>
                <td>{{ movie.poster }}</td>
            </tr>
            <tr>
                <th>French_title</th>
                <td>{{ movie.frenchTitle }}</td>
            </tr>
            <tr>
                <th>Original_title</th>
                <td>{{ movie.originalTitle }}</td>
            </tr>
            <tr>
                <th>Year</th>
                <td>{{ movie.year }}</td>
            </tr>
            <tr>
                <th>Prod_countries</th>
                <td>{{ movie.prodCountries }}</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>{{ movie.duration }}</td>
            </tr>
            <tr>
                <th>Pitch</th>
                <td>{{ movie.pitch }}</td>
            </tr>
            <tr>
                <th>Review</th>
                <td>{{ movie.review }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_movies_index') }}">back to list</a>

    <a href="{{ path('app_movies_edit', {'id': movie.id}) }}">edit</a>

    {{ include('movies/_delete_form.html.twig') }}

    </main>    
{% endblock %}